### ISSUE TITLE
Configuration for Ubuntu and passing dhcp/bootp parameters

### ISSUE THREAD

**Issue by vogelfreiheit** [skom91/initramfs-tools-network-hook#1]
Have you tested this with Ubuntu Server (any of the LTS releases, 18.x preferably)?

Are you using the kernel command line ip= parameter independently? If so, what do you use as the interface name? iface.X?

It's quite shameful neither Debian nor Ubuntu support bonding and VLANs in their initramfs environment when this has been standard in dracut for years now.

Thanks!

**Comment by skom91** [comment]
I have not tested this with Ubuntu, but i'm quite sure it will work. Maybe you can report this.

I just commited a few changes i've made, now you can also configure the Bonding Driver Options.

You can use the ip= parameter independently.
The naming scheme for VLAN ist `$SOURCE_IFACE.$VLAN_ID`. You can see it in `etc/initramfs-tools/scripts/init-top/vlan`

**Comment by vogelfreiheit** [comment]
I'll give it a go, but the hook causes problems (/conf/ is not a valid path):

   grep: /conf/initramfs.conf: No such file or directory
   grep: /conf/initramfs.conf: No such file or directory

**Comment by skom91** [comment]
Thanks for the report, i fixed the error with the new commit. I also tested the vlan hook successfull on Ubuntu18.10.

**Comment by vogelfreiheit** [comment]
Nice! Thanks :)
