### ISSUE TITLE
On Debian 9 with encrypted root, bonding script loads after cryptsetup

### ISSUE THREAD

**Issue by malakudi** [skom91/initramfs-tools-network-hook#2]
Script to setup the bonding loads after dropbear/cryptsetup on Debian 9 (haven't checked on 10) and you can't unlock encrypted root from ssh on bonded interface.
I fixed it by moving bond script to local-top instead - I don't know if this is the correct way.

After this change, bonded networking is loaded before dropbear/cryptsetup and remote unlock works, BUT bonded interface doesn't work after system start because ifup bond0 from Debian9 finds the slave devices allready in the bond0 device and fails. I fixed this by adding a bond script in scripts/local-bottom, like this:
```
#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

if grep -q ^BOND= /conf/initramfs.conf; then
    . /conf/initramfs.conf
fi

for BOND_IFACE in ${BOND:-*}; do
    BOND_DEVICE=$(echo $BOND_IFACE | cut -d":" -f1)
    BOND_SLAVES=$(echo $BOND_IFACE | cut -d":" -f2 | sed "s/,/ /g" )
    ifenslave -d $BOND_DEVICE $BOND_SLAVES
done

exit 0
```

Maybe different approach is more correct, but that's how I made it work. Expecting your comments. Thank you

**Comment by sRlinux** [comment]
Hello malakudi, can you please provide your initramf.conf?

`BOND="bond0:eth0,eth1"
BOND_MODE="mode=802.3ad miimon=100"
VLAN="bond0:10"
IP=:::::bond0:dhcp
DEVICE=bond0
`
mine is not working :-(

**Comment by malakudi** [comment]
> Hello malakudi, can you please provide your initramf.conf?
> 
> ```
> BOND_MODE="mode=802.3ad miimon=100"
> VLAN="bond0:10"
> IP=:::::bond0:dhcp
> DEVICE=bond0
> ```
> 
> mine is not working :-(

You want both vlan and bonding? Haven't tested such setup, I only needed bonding.
BOND="bond0:enp175s0f0,enp175s0f1"
BOND_MODE="mode=802.3ad xmit_hash_policy=layer3+4 miimon=100"
IP=:::::bond0:dhcp
I don't set DEVICE to bond0, I leave it unset.

**Comment by skom91** [comment]
Hi,
Debian 9 worked for me, but now i got an issue on debian 10. I'll try to fix this next week.

**Comment by skom91** [comment]
I updated the scripts to a newer version and for me with debian 10 everything is working again.
I used the solution from malakudi, thanks for your help. I just added a line to delete the bond interface at the end. This is not necessary in most configurations but then everything is in a clear state.

**Comment by sRlinux** [comment]
any clue about my issue? :-\

**Comment by skom91** [comment]
Your initramfs.conf does not look correct at all. You need a line with the configuration of your bond interface like:
    BOND="bond0:eth0,eth1"
Otherwise no bond device is created.

**Comment by sRlinux** [comment]
ok thanks, i try it when i am back at the server location. i will report!
